name: gmetl_cfs
channels:
  - conda-forge
# These are required for developing the package (running the tests, building
# the documentation) but not necessarily required for _using_ it.
dependencies:
  - numpy
  - xarray

